# Generated by Django 5.2.7 on 2025-11-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skill',
            field=models.ManyToManyField(related_name='projects', to='skill.skill'),
        ),
    ]
