# Generated by Django 5.2.7 on 2025-11-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_created_at'),
        ('skill', '0002_skillcategory_alter_skill_options_remove_skill_users_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-order', '-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='devops_tools',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category__name': 'devops'}, related_name='project_devops', to='skill.skill'),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('real', 'Real loyiha'), ('practice', 'Tajriba loyihasi')], default='practice', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='work_type',
            field=models.CharField(choices=[('team', 'Jamoaviy ish'), ('active', 'Hozirgi ish'), ('learning', "O'rganish uchun"), ('personal', 'Shaxsiy loyiha')], default='personal', max_length=20),
        ),
    ]
