# Generated by Django 5.2.7 on 2025-11-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_options_project_devops_tools_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='devops_tools',
        ),
    ]
