# Generated by Django 5.2.7 on 2025-11-04 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('pre-intermediate', 'Pre-Intermediate'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('native', 'Native')], default='beginner', max_length=20)),
                ('users', models.ManyToManyField(related_name='languages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
