# Generated by Django 5.2.7 on 2025-11-04 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='languages', to=settings.AUTH_USER_MODEL),
        ),
    ]
