# Generated by Django 5.2.7 on 2025-11-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_education_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('bachelor', 'Bakalavr'), ('master', 'Magistr'), ('Doktorantura', 'Phd'), ('professional_course', 'Kasbiy kurs'), ('diploma', 'Diplom'), ('certificate', 'Sertifikat')], default='bachelor', max_length=30, verbose_name='Daraja'),
        ),
    ]
