# Generated by Django 5.2.7 on 2025-11-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_education_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('bachelor', 'Bakalavr'), ('master', 'Magistr'), ('phd', 'PhD'), ('professional_course', 'Kasbiy kurs')], default='bachelor', max_length=30, verbose_name='Daraja'),
        ),
    ]
