# Generated by Django 5.2.7 on 2025-11-05 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(
                    choices=[
                        ('programming', 'Dasturlash tillari'),
                        ('database', "Ma'lumotlar bazasi"),
                        ('framework', 'Framework va kutubxonalar'),
                        ('devops', 'DevOps vositalari'),
                        ('other', 'Boshqa'),
                    ],
                    max_length=100,
                    unique=True
                )),
                ('display_name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'skill_category',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category__order', 'name']},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='users',
        ),
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='skills',
                to='skill.skillcategory'
            ),
        ),
    ]
