# Generated by Django 5.2.7 on 2025-11-05 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_skillcategory_alter_skill_options_remove_skill_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
