# Generated by Django 5.2.7 on 2025-11-05 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0004_alter_skill_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillcategory',
            name='display_name',
        ),
    ]
