# Generated by Django 5.2.7 on 2025-11-05 07:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0005_remove_skillcategory_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('programming', 'Dasturlash tillari'), ('database', "Ma'lumotlar bazasi"), ('framework', 'Framework va kutubxonalar'), ('devops', 'DevOps vositalari'), ('other', 'Boshqa')], help_text='Ko‘nikma tegishli bo‘lgan toifa.', max_length=100),
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Ko‘nikma', 'verbose_name_plural': 'Ko‘nikmalar'},
        ),
        migrations.AlterField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Ko‘nikma yaratilgan sana va vaqt.'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text='Ko‘nikma nomi (masalan: Python, Django, Git, Docker).', max_length=100),
        ),
        migrations.DeleteModel(
            name='SkillCategory',
        ),
    ]
